repos:
- repo: https://github.com/fastai/nbdev
  rev: 2.3.32
  hooks:
  - id: nbdev_clean
  - id: nbdev_export

- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.9.1
  hooks:
   - id: nbqa-black
   - id: nbqa-pyupgrade
   - id: nbqa-isort
     args: [--profile=black]