# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/02360018_final_project',
                'doc_host': 'https://techofer.github.io',
                'git_url': 'https://github.com/techofer/02360018_final_project',
                'lib_path': 'electricity_market'},
  'syms': {'electricity_market.electricity_market_env': {}, 'electricity_market.electricity_market_player': {}}}
