"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_electricity_market_player.ipynb.

# %% auto 0
__all__ = ['env', 'model', 'mean_reward', 'std_reward']

# %% ../nbs/01_electricity_market_player.ipynb 3
import gymnasium as gym
from stable_baselines3 import PPO
from stable_baselines3.common.evaluation import evaluate_policy
from stable_baselines3.ppo.policies import MlpPolicy

from .electricity_market_env import ElectricityMarketEnv


# %% ../nbs/01_electricity_market_player.ipynb 4
env = ElectricityMarketEnv({
    "battery_capacity": 10000000,
    "init_state_of_charge": 4000000,
    "init_current_demand_of_electricity": 1000,
    "init_current_price": 100
})

env.reset()

model = PPO(MlpPolicy, env, verbose=0)


model.learn(total_timesteps=10_000)
mean_reward, std_reward = evaluate_policy(model, env, n_eval_episodes=100, warn=False)

print(f"mean_reward:{mean_reward:.2f} +/- {std_reward:.2f}")

