# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_utils.ipynb.

# %% auto 0
__all__ = ['EvaluationData']

# %% ../nbs/05_utils.ipynb 3
from dataclasses import dataclass

# %% ../nbs/05_utils.ipynb 4
@dataclass
class EvaluationData:
    episodes: list[int]
    rewards: list[float]
